//Copyright (C) 2020  Germán Fuentes Capella

package files

import (
	"os"
	"text/template"
)

// Writes a file with the content generated by the template
func WriteFromTemplate(path string, templateTxt string, data interface{}) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	tmpl, err := template.New(path).Parse(templateTxt)
	if err != nil {
		return err
	}

	err = tmpl.Execute(file, data)
	return err
}
